- build: 1.5.4/centos/7
  image:
    - mesoscloud/logstash:1.5.4-centos-7
    - mesoscloud/logstash:1.5.4-centos
    - mesoscloud/logstash:1.5.4
    - mesoscloud/logstash:latest

- build: 1.5.4/ubuntu/14.04
  image:
    - mesoscloud/logstash:1.5.4-ubuntu-14.04
    - mesoscloud/logstash:1.5.4-ubuntu

- build: 1.5.3/centos/7
  image:
    - mesoscloud/logstash:1.5.3-centos-7
    - mesoscloud/logstash:1.5.3-centos
    - mesoscloud/logstash:1.5.3

- build: 1.5.3/ubuntu/14.04
  image:
    - mesoscloud/logstash:1.5.3-ubuntu-14.04
    - mesoscloud/logstash:1.5.3-ubuntu


- tests:
    - cmd: logstash -V
